[build]
  command = "react-scripts build"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/stripe'
  status = 200

[[redirects]]
  from = '/bio'
  to = '/home'
  status = 200

[[redirects]]
  from = '/contact'
  to = '/home'
  status = 200