[build]
  command = "react-scripts build"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200

[[redirects]]
  from = '/bio'
  to = '/home'
  status = 200

[[redirects]]
  from = '/bio'
  to = '/home'
  status = 200

[[plugins]]
package = "@netlify/plugin-nextjs"