
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = '/api/react'
  to = '/.netlify/functions/:splat'
  status = 200

  from= "/contact"
  to = "/index.html"
  status= 200