

[build]
  command = "# no build command"
  functions = "netlify/function"
  publish = "."

[[redirects]]
  from = '/api/*'
  to = '/.netlify/function/:splat'
  status = 200

  from= "/contact"
  to = "/index.html"
  status= 200